### ISSUE TITLE
It is helpful to show an example how to create a simple skin animation

### ISSUE THREAD

**Issue by xiazhibin** [filonik/pygltf#3]
As a beginner, I am not familiar with creating a skin animation with `pygltf`.
It is very helpful for me.
Thanks a lot!!

**Comment by filonik** [comment]
Sure, I can look into that when I get a chance. In the meantime, perhaps these will help?

https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_019_SimpleSkin.md

https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_020_Skins.md

**Comment by xiazhibin** [comment]
Thanks
